name: OSV Scanner
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  osv-scanner:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Run OSV Scanner
        uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@a345acffa64b0eaede81a3d9aae6141214d9c8fc
        secrets: inherit
        with:
          scan-args: --config=./osv-scanner.toml -r ./
          fail-on-vuln: true
          results-file-name: results.sarif
          download-artifact: false
          export-results: true
          runs-on: ubuntu-latest
      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@3ea06614dafe36dec890db3446326e0d40ce53d4
        with:
          sarif_file: results.sarif
          category: osv-scanner
